### ISSUE TITLE
getting error - website unreachable

### ISSUE THREAD

**Issue by tshrinivasan** [stephenraj314/Bs4scraping#1]
python3 Scrapper_noolulagam.py 
webpage is unreachable

I get the above error on my ubuntu 20.04 machine.

**Comment by stephenraj314** [comment]
webpage unreachable error resolved sir

**Comment by stephenraj314** [comment]
> 
> 
> python3 Scrapper_noolulagam.py
> webpage is unreachable
> 
> I get the above error on my ubuntu 20.04 machine.

webpage unreachable error resolved sir
